spring:
  config:
    import: classpath:version.properties
  application:
    name: diet-coach

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # 콘솔 색상 설정
  output:
    ansi:
      enabled: always

  ai:
    openai:
      chat:
        options:
          model: gpt-4o
          temperature: 0.0

  profiles:
    active: local
