spring:
  application:
    name: diet-coach

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # 콘솔 색상 설정
  output:
    ansi:
      enabled: always

  profiles:
    active: dev
